# spring:
#   datasource:
#     driver-class-name: com.mysql.jdbc.Driver
#     username: root
#     url: jdbc:mysql://localhost:3306/dcbapp
#     password: suad2001
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
# server:
#   port: 3000
